### PR TITLE
Emily

### PR DESCRIPTION
**Pull request by EmilyVam**

### CODE REVIEW

**Comment by davclark** [comment]
To say a little more about what's going on here - most of the changes are just moving files to make the repo easier to manage.

We may also not want to merge the BIDS-collaborative gitter chat room - though perhaps that's fine (but we should definitely change the bit in the README that says this is a fork if it's meant to go upstream!)

**Comment by jbpoline** [comment]
So, I realized that I am in a poor state to test these PR, because my install of brainspell is a clone of Roberto's and not installed on a VM.  Will add bids-collaborative as a remote and let you know if I can test things properly asap.

**Comment by davclark** [comment]
@jbpoline note that the pull request moves the root directory into `site` - so you'll need to update your configurations!

**Comment by jbpoline** [comment]
yes, and the password for mysql is not the same, I would need to change this as well.  I think I should add the VM and do the PR reviews there - this way I can give feedback on the instructions :)

**Comment by davclark** [comment]
We left the password the same as in @r03ert0's config!

**Comment by davclark** [comment]
Sadly, the complexity of adding this in seems to be beyond us at this point. I'm closing for now.

**Pull request closed without merging**
