### PR TITLE
Fix server + port URL for php requests

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by jbpoline** [comment]
Just tried it - works fine until you try to do a search: I then get :

> Impossible to open an index at /var/www/html/php/LuceneIndex fopen(/var/www/html/php/LuceneIndex/read.lock.file): failed to open stream: Permission denied

Not sure where these permissions should be set (if they should :) 

should something like 

RUN find /var/www/html -type d -exec chmod u+rwx,g+rx,o+rx {} +
RUN find /var/www/html -type f -exec chmod u+rw,g+r,o+r {} +

be added ?

**Comment by stefanv** [comment]
That's a different problem. You need

chmod o+w LuceneIndex

**Comment by jbpoline** [comment]
chmod a+w site/php/Lucene/Index/\* worked :)  thanks - 

Should this be run in the apache Dokerfile ?  Just curious if others had to do it as well: was this needed on OSX and Windows ?

**Comment by stefanv** [comment]
Not in the Dockerfile, perhaps, but rather in the installation
instructions.

**Pull request merged**
